- .travis.yml
- Dockerfile
- README.md
@tsibley ---
Just updating you on why I did things the way I did. I had noticed that automated builds were taking ~40 minutes on Docker Hub. This was because Docker Hub does not attempt any caching for automated builds. Consequently, I experimented with running automated builds on Quay.io and Docker Cloud, which both theoretically allow caching. However, I couldn't get it to work with either. In both there is no control over the `docker build` command called after a GitHub push.
Consequently, I moved things over to Travis CI, which provides full control over the build. I was able to get caching working there via `--cache-from`. Builds now take 3 minutes if nothing has changed and ~6 minutes if something has. If the Travis CI build is successful, then `docker push` is run to update the …
> Improve caching and automate builds via Travis CI

- .travis.yml
For jobs triggered by push, $TRAVIS_BRANCH is the branch name, as
expected.
For jobs triggered by PRs, $TRAVIS_BRANCH is the _destination_ branch
name, i.e. the stable branch (usually master) that the feature branch is
intended to be merged into (and Travis tests the merge).
More details here, as noted by James:
https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/
We don't ever want to update our default live Docker images for PRs.  We
only want to do so after PRs/branches are merged and pushed to master.
> Fix our usage of $TRAVIS_BRANCH

- Dockerfile
@tsibley ---
We want a stable call to `nextstrain view`. Better to have the Docker image `latest` tag refer to `release` branch of auspice and only update the Docker image when `release` branch is updated, rather than when `master` is updated.
Currently, auspice Travis CI script properly pings the `docker-base` rebuild only when auspice `release` is pushed: https://github.com/nextstrain/auspice/blob/master/.travis.yml#L11. This change brings `docker-base` in line.
Once we have a `release` branch and proper versioning in augur, I would swap augur to do the same.
> Build image using auspice release branch

- Dockerfile
- devel/build
Metadata is useful for identifying images later, especially if they've
been untagged locally by newer versions.
The nextstrain-cli also needs to be able to identify our images for
automatic pruning.  It will use org.nextstrain.image.name to do this.
> Add labels to the image to track metadata

- Dockerfile
- devel/download-repo
These are useful to have for debugging and inspecting what's in an
image.  Baking them into the image itself is handy because it means they
won't be misleading when/if a local copy of auspice or augur is
overlaid.
Resolves #13.
> Record versions/git ids of individual Nextstrain components

- Dockerfile
Checkpoints are a useful newer feature of Snakemake which are only available on 5.4.0 and newer.
> Upgrade Snakemake to 5.5.2 (the latest stable version)

- Dockerfile
Note that this isn't intended to support nested builds.
> Install our own Nextstrain CLI so builds can do things like `nextstrain deploy`

- Dockerfile
The current Docker image has Snakemake version 5.8.1, but when running builds on AWS, we need access to the `--set-threads` argument that was added in version 5.10.0. This PR updates the Docker image to this later version of Snakemake which also happens to be the latest version currently supported by augur.
> Update snakemake to support --set-threads argument

- Dockerfile
Alpine Linux uses musl libc instead of glibc which means it cannot use most
pre-built Python wheels for glibc-based Linux distributions [1]. As a result, Python
packages need to be built from source, leading to longer build times and
increased complexity in the Dockerfile for more complex packages. For complex
packages like opencv-python, building from source is especially non-trivial.
This commit ports the existing Alpine-based Dockerfile to a minimal Debian-based
file with pre-installed Python 3 (the official Python Docker image) and removes
dependencies that were originally required to build Python packages from
sources (e.g., cvxopt) where installation from a wheel is now possible.
This commit also removes all explicit references to Python 2 dependencies, as
fauna is compatible enough …
> Replace Alpine-based image with a Debian-based image

- Dockerfile
The ncov workflow annotates epiweeks from dates to more effectively communicate dates with epidemiologists and allow epi users to color and filter data by these annotations. This commit adds the Python `epiweeks` package as a dependency, to support epiweek annotations for ncov workflow users who rely on the Docker image.
Required for https://github.com/nextstrain/ncov/pull/703
Related to https://github.com/nextstrain/docker-base/issues/33
> Add epiweeks as a workflow-specific dependency

- Dockerfile
The only notable difference at the moment is the version of cvxopt,
which is 1.2.x here, but 1.1.x in Augur's setup.py at the moment.
@huddlej notes that the Augur bioconda recipe actually uses 1.x and
Augur's setup.py should be separately updated to reflect a more lenient
version.
That original reason Augur's deps were explicitly inlined into the
Dockerfile here was to avoid lengthy image rebuilds.  That was done
because several of the deps didn't have wheels for Alpine, so had to be
compiled from source.  With the new Debian image base, we should be able
to rely on wheels, so installing the deps every time won't be much of a
burden and very much worth the simplicity of having a single source of
truth.
> Install Augur's "full" extra deps automatically instead of inlining them separately

- Dockerfile
This adds Pangolin to nextstrain-base docker image. I'm not sure specifically which version of pangolin we want to include, so I used the versions mentioned in the GitHub issue. Just let me know if I should update this!
Fixes #33 
I've rebuilt the docker image and Pangolin runs successfully:
```
% ./devel/build
<output omitted>
% docker run -ti --rm=true nextstrain/base -- sh -c 'pangolin /usr/local/lib/python3.7/site-packages/pangolin/data/reference.fasta 2> /dev/null && echo output: && cat lineage_report.csv'
Found the snakefile
Do things with sam files
Usage:
gofasta sam [flags]
gofasta sam [command]
Available Commands:
indels       Parse a SAM file for raw indel information
toMultiAlign Convert a SAM file to a multiple alignment in fasta format
toPairAlign  convert a SAM file to …
```
> Add Pangolin to nextstrain-base docker image

- Dockerfile
The pango-designation library [had a packaging bug](https://github.com/cov-lineages/pango-designation/issues/415) that was causing some ncov-ingest tools to break when they ran inside the latest ncov base image. They've since patched the bug, and this PR updates pango-designation to use the current tip of the master branch (pending a new official release)
**Before:**
```
% ./devel/build
% docker run -ti --rm=true docker.io/nextstrain/base bash
Cloning into '/ncov-ingest'...
Traceback (most recent call last):
File "/ncov-ingest/bin/transform-gisaid", line 12, in <module>
from utils.transform import (
ModuleNotFoundError: No module named 'utils.transform'
```
**After:**
```
% ./devel/build
% docker run -ti --rm=true docker.io/nextstrain/base bash
Cloning into '/ncov-ingest'...
usage: …
```
> Install a patched version of pango-designation to fix ncov-ingest

- Dockerfile
This adds Nextclade to nextstrain-base docker image in support of some of the work that @sidneymbell is doing in ncov.
https://github.com/nextstrain/ncov/issues/811
I've rebuilt the image and the nextclade CLI works in a container launched from it.
```
% ./devel/build
=> exporting to image                                                                                           0.0s
=> => exporting layers                                                                                          0.0s
=> => writing image sha256:dba5d6d91ca4a9625d7ed08c1a66c2efcbb59f3a77a19d903bf5e9907c892def                     0.0s
=> => naming to docker.io/nextstrain/base                                                                       0.0s
% docker run docker.io/nextstrain/base nextclade --help
Viral …
```
> Add nextclade CLI

- Dockerfile
Adds Python package for Google Cloud Storage. This package is required for Snakemake to access remote files storage on Google Cloud Storage, for example when fetching remote files stored on GS from a Terra workflow job.
When this package is not installed, Snakemake will produce the following error:
```
Building DAG of jobs...
InputFunctionException in line 60 of /nextstrain/build/workflow/snakemake_rules/main_workflow.smk:
WorkflowError: The Python 3 package 'google-cloud-sdk' needs to be installed to use GS remote() file functionality. No module named 'google'
Wildcards:
origin=example_data
```
When the package is installed and credentials are not configured to access the GS data, Snakemake produces the following error:
```
DefaultCredentialsError: Could not automatically determine …
```
> Add Google Cloud Storage Python package

- Dockerfile
- devel/latest-augur-release-tag
The "release" branch was recently removed.¹  Instead, use the Git tag
for the latest stable version released to PyPI.
There's a larger discussion to be had about if it makes any sense any
more for Augur to be installed from Git instead of PyPI (and
correspondingly, Auspice from NPM), but that's for another time.
¹ https://github.com/nextstrain/augur/pull/913
> Install Augur from the latest stable version tag instead of the "release" branch

- Dockerfile
Adds regularly used utilities to the base image, so they can be used in our workflows.
I opted to use prebuilt binaries here instead of setting up dev environments for D and Go, to support these different tools. If building from source is seen as a valuable step, we'll need to expand this PR a bit to include those environments.
You can test this image locally by starting Docker and running:
```
nextstrain shell --image nextstrain/base:branch-add-csv-tsv-seq-utils .
```
Then try any of these new utilities.
> Add tsv-utils, csvtk, and seqkit to image

- Dockerfile
Having both available will aid transitions from v1 → v2, including
ours.¹ At some point we'll switch the default to v2 but still keep v1
around.
¹ https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1655488730483759?thread_ts=1655459762.164449&cid=C7SDVPBLZ
Obsoletes https://github.com/nextstrain/docker-base/pull/43.
> Provide nextclade2 and nextalign2 while retaining the default of v1

- Dockerfile
The owner ids in the tar files are meaningless and whatever the user ids
happened to be on the systems creating the archives.  This has no
functional consequences, but since we noticed it¹, fix it.
¹ https://github.com/nextstrain/docker-base/pull/51#issuecomment-1158299206
> Don't preserve the owner when unpacking tar archives

- Dockerfile
This version fixes a crash on low-quality mpx sequences. We can now use gnu flavor of Linux binaries, since the compatibility was improved.
https://bedfordlab.slack.com/archives/C03G8HQEV18/p1655914687522139
> Upgrade nextclade and nextalign to 2.0.0-beta.7, use gnu flavor

- Dockerfile
Issue: https://github.com/nextstrain/ncov/issues/968
This switches symlinks `nextclade` and `nextalign` to point to v2. This means that all the places where `nextclade2` and `nextalign2` were used can be replaced to simply `nextclade` and `nextalign`, which would resolve the issue  https://github.com/nextstrain/ncov/issues/968.
The base image and all the derived images have to be rebuild for it to work.
Sister PRs:
- https://github.com/nextstrain/ncov/pull/969
- https://github.com/nextstrain/monkeypox/pull/91
> Set Nextclade v2 as default, upgrade to Nextclade 2.2.0

- Dockerfile
Resolves <https://github.com/nextstrain/docker-base/issues/72>.
> Install less(1) so there's a reasonable pager for `nextstrain shell`

- devel/build
- devel/tag
This makes it easier to support multi-platform builds in the future, and
explicitly sets the currently used platform (linux/amd64).
Motivated by https://github.com/nextstrain/docker-base/pull/46#pullrequestreview-1005012188, but using `docker buildx create` in the script instead of `setup-buildx-action`.
- Supersedes/closes #46
- closes #48
- Preparing for #35
- Closes #70
See checks.
> Use buildx create+build

- devel/push
This check was placed incorrectly in 7d4daa92af7269240a349bca5c56589f27563bee.
Two tags can point to the same image and if one of them is pushed first,
the other will error even though both were "new" at the start of the
script.
- Addresses issue in https://github.com/nextstrain/docker-base/pull/78#discussion_r953171715
> Check all tags before pushing

- Dockerfile
- bashrc
- prompt.sh
The upshot of this is that any interactive Bash session gets the prompt,
not just a login session.  It also makes overriding the file in newer
`nextstrain shell` versions a bit less custom, since /etc/bash.bashrc is
the standard Debian/Ubuntu system bashrc path.
> Configure the prompt using bashrc instead of a profile.d snippet

- Dockerfile
It has been removed in https://github.com/nextstrain/augur/pull/1035.
> Remove usage of augur full dependency list

- devel/build
Import caches from both `latest` and `$tag` (if available) on registry for caching.
Reference: https://docs.docker.com/engine/reference/commandline/buildx_build/#cache-from
- Closes #57
> Improve `--cache-from` caching

- Dockerfile
Without this change, Node.js v10 is installed. That version reached end of life on 2021-04-30 [[1]]. Node.js v14 is the oldest version that is currently maintained.
Use this in (1) the builder stage to install/build Auspice, and (2) the final stage to make Auspice usable with the same Node.js version.
Note that `apt-get install npm` is not necessary since the `nodejs` package contains both the `node` and `npm` binaries.
[1]: https://github.com/nodejs/Release#end-of-life-releases
```
$ docker run nextstrain/base:build-20221005T235113Z node --version
v10.24.0
```
_N/A_
> Install Node.js version 14

- Dockerfile
- entrypoint
Switch to non-root user (nextstrain) in entrypoint exec chain
Restores default use of a non-root user even for ad-hoc image uses without getting in the way (like USER does) of downstream images inheriting from us (see previous commit).
setpriv is part of util-linux, which is installed by default but is also installed explicitly in case that changes.  It is an exec-chaining program explicitly designed for modifying privs normally retained across an exec boundary.
A chown ensures that /nextstrain/build is writable by the nextstrain user.  This doesn't matter for the local Docker runtime (e.g. via `nextstrain build --docker`) because we mount over the container's /nextstrain/build with the build directory from the host (and run as the host user's uid/gid).  But for the AWS Batch runtime we …
> Non-root user, trois

- devel/build
The builder image does not need to look for layers in the final image.
- #57
Note that I don't expect any significant performance improvement from this change, but at the least this reduces unnecessary cache retrieval.
> Remove final image cache source from builder image

- Dockerfile
Some improvements to the Dockerfile.
- #57
- Improves caching by handling version-pinned software before `CACHE_DATE`
```sh
docker run nextstrain/base:build-20221013T234036Z ls -lR --time-style='+' /usr/local/{bin,libexec,share} > old.txt
docker run nextstrain/base:branch-victorlin-organize-dockerfile ls -lR --time-style='+' /usr/local/{bin,libexec,share} > new.txt
diff old.txt new.txt
```
> Re-organize Dockerfile

- Dockerfile
Currently, the reasoning on why each package is used
1. can be deduced from direct references in the Dockerfile (e.g. curl), or
2. can be deduced from git blame (e.g. jq: c256a30eccf08ba5c245656a2b2bc3b1f2f713f9), or
3. is unclear.
To make this easier, document why each package is installed.
_N/A_
> Annotate package installs

- Dockerfile
According to the official ["Dockerfile best practices" guide](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/), it's a good idea to pair apt-get update with apt-get install in the same RUN statement.
This is mostly a future-proofing change, as the current script at https://deb.nodesource.com/setup_14.x already calls apt-get update. I think caching problems would only arise if (1) the Node.js version is updated, (2) the setup script no longer call apt-get update, and (3) the package install list is updated so that at least one package is missing from the APT cache pulled in the last RUN statement, which may be from an old Docker cache.
_N/A_
> Improve Node.js installation

- Dockerfile
Debian 10 reaches EOL in August
This helps getting more up to date versions of things like `zstd` installed by `apt install`
Is there a reason we need to use Debian 10?
> chore: switch to Debian 11 (bullseye) from Debian 10 (buster)

- Dockerfile
3.7 was chosen in early 2020, when 3.8 was only a few months old.  3.10 is now a year old, and we already use it in other Nextstrain contexts.
The motivation for this came from @jgadling who wanted to take advantage of newer Python typing features in scripts running alongside Nextstrain in this Docker image.
(Change made by @jgadling, commit written by @tsibley.)
(Rework of #100 to squash commits and write a commit message with more rationale.)
> Upgrade Python from 3.7 to 3.10

- Dockerfile
Move the Nextstrain CLI installation to below the CACHE_DATE so that it does not stay in the cache indefinitely. I believe this was the intention when we stopped pinning the Nextstrain CLI to a specific version.
> Uncache Nextstrain CLI

- Dockerfile
Creating PR to start some general discussions:
1. Should `evofr` be added to docker-base or should we create a separate forecasts image? 
I've added it here to easily test with the `nextstrain/base:branch-evofr` image, but I'm not sure if we should actually add it to docker-base since it's such a niche tool. We are currently only using `evofr` for [forecasts-ncov](https://github.com/nextstrain/forecasts-ncov), but we will probably expand to other pathogens. It's unclear to me how much it will get used by outside Nextstrain users. 
1. How often should the image get updated? 
Since `evofr` is still in development, would it make sense to add a GH Action to the `evofr` repo to build the image on each push to the main branch?
> Add `evofr` for forecasts

- Dockerfile
pyfastx is required by Augur starting with 18.2.0.
We need the build and run time requirements installed because wheels for pyfastx aren't currently built for Python 3.10¹, which is what our image uses.
¹ https://github.com/lmdu/pyfastx/issues/47
> Add build and run time requirements for pyfastx

- devel/delete-from-ghcr.js
See commit messages.
None – I stumbled across this while testing other PRs.
> delete-from-ghcr: Improve error handling

- devel/build
Currently, only images available locally or on the destination registry (Docker Hub) are used for caching. This was fine before the usage of an intermediate directory. Now that built images are no longer available locally, there are two new issues:
1. The final stage does not use the cached builder stage since it is no longer available from cache sources.
2. Local development is slower since the built image layers are not available from cache sources.
Adding the intermediate registry as a cache source fixes these.
- Follow-up to #103
> build: Use intermediate registry as a cache source

- Dockerfile
tsv-utils require unix line endings, otherwise crash ncov-ingest requires dos2unix as a result
> Install dos2unix via apt-get

- Dockerfile
The NCBI Datasets command line tools will be used to fetch virus packages¹ for various pathogen ingest pipelines.
The `datasets` command fetches the virus packages and the `dataformat` command transforms the nested JSON data structure to flat TSV metadata files.
¹ https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/data-packages/virus-genome/
> Add NCBI Datasets CLI

- .github/workflows/ci.yml
- Dockerfile
- README.md
- builder-scripts/target-triple
- devel/build
Currently, the Docker images are built for `linux/amd64` only. These changes build the Docker images for both `linux/amd64` and `linux/arm64`.
This will substantially improve the performance of the Docker runtime for Apple silicon users, as it no longer needs to use slow Intel architecture emulation. A major drawback is the increased build time since building the `linux/arm64` image on a `linux/amd64` GitHub Actions runner requires emulation. However, IMO the benefit to users outweighs the increased build-time on our end, which can be improved in the future.
Cross-compilation (#98) is a major build-time improvement on top of this PR to be considered separately.
- Resolves #35
- Supercedes/closes #48
- Local registry? ([ref](https://github.com/nextstrain/docker-base/pull/50#discussion_r9555 …
> Support building multi-platform images and add `linux/arm64`

- Dockerfile
As far as I can tell from the official software page¹, no dependencies are documented.
However, there are (unofficial?) Linux packages²³ that list libc6 and libgomp1 as dependencies. Adding the latter for now since `augur tree --method fasttree` fails with the error:
FastTreeDblMP: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
¹ http://www.microbesonline.org/fasttree/
² https://packages.ubuntu.com/focal/fasttree
³ https://packages.debian.org/sid/science/fasttree
- Fixes #123
> Add libgomp1 for running FastTree

- Dockerfile
Even though TreeTime is implicitly installed in the builder stage as a dependency of Augur, it's more proper to install it explicitly if downstream workflows/analyses will be using it directly.
Also, copy the CLI executable to the final image to enable downstream workflows/analyses to use it directly.
Resolves #134
> Add TreeTime

- .github/workflows/ci.yml
- Dockerfile
- README.md
- devel/validate-platforms
Start off by checking software in which versions are known to be time-varying.
- Addresses the main point in #128.
Tested locally:
1. With a tag known to have differing Augur versions.
<details>
<summary>
Commands and output
</summary>
```
% ./devel/validate-platforms -r docker.io -t build-20230217T192833Z
[linux/amd64] Pulling image...
docker.io/nextstrain/base:build-20230217T192833Z
[linux/amd64] Checking that the platform is expected...
[linux/amd64] Generating report file: /var/folders/rk/s2p6nv1d13lcf0dynjkvxyl80000gp/T/validate-platforms-XXXXXX.WEPtnBnz/linux/amd64
[linux/amd64] Determining software versions...
[linux/arm64] Pulling image...
docker.io/nextstrain/base:build-20230217T192833Z
[linux/arm64] Checking that the platform is expected...
[linux/arm64] Generating report file: …
```
> CI: Validate images across platforms

- devel/build
Provenance metadata was newly enabled by default in buildx 0.10.0¹ and entails switching from older, Docker image manifest lists (application/vnd.docker.distribution.manifest.list.v2+json) to the newer, but roughly equivalent-in-concept, OCI image indexes (application/vnd.oci.image.index.v1+json).²
This switch happened automatically for us between these two builds:
nextstrain/base:build-20230119T003940Z
nextstrain/base:build-20230321T203820Z
due to an upgrade of buildx from 0.9.1 → 0.10.0 on the GitHub Actions runners we use for CI.
Unfortunately, Singularity doesn't support OCI image indexes (i.e. multi-platform images) until 3.6.0.³  While we'll likely need to require a newer Singularity version at some point anyway⁴, disabling the provenance metadata for now should restore …
> build: Disable SLSA Provenance metadata for our images

- Dockerfile
Previously, cvxopt was unusable on the arm64 variant with this error:
ImportError: liblapack.so.3: cannot open shared object file: No such file or directory
This makes sense because the CVXOPT installation instructions state that BLAS and LAPACK are required¹ (these are provided by the OpenBLAS package). In c1515608e17fc1f7d933854901ab2c81f51b696e, they were only installed in the builder image since I did not realize they were required during run time.
Interestingly, cvxopt was already usable on the amd64 variant without this change. I'm not sure why.
¹ https://cvxopt.org/install/#building-and-installing-from-source
- Fixes #142
> Fix arm64 CVXOPT installation

- .github/workflows/ci.yml
A useful check for if new images will break our pathogen builds.
I included all pathogen repos that already use our pathogen-repo-ci reusable workflow.  It should be minimal effort to maintain this list over time—I expect it to only grow—but perhaps in the future we will want to abstract it out into a shared list of known pathogen repos.
I don't like that we have to copy the build-args for a few of the repos here since it'll be easy for this copy to diverge from the repo's authoritative build-args, but it's necessary for now.  Over time as we work towards increased automation of pathogen builds, I think we can get rid of this build-args copy by further standardizing how each repo configures itself for automation.  For example, instead of specifying build-args in a repo's CI workflow, the …
> ci: Test pathogen repo CI builds with the final image

- .github/workflows/ci.yml
This makes them advisory-only, as they're currently broken.¹
We may also opt to leave them advisory-only longer term, as they might
be noisy and not fit for stopping an image release.
Idea for the pass thru this uses from @joverlee521.²
Related-to: <https://github.com/nextstrain/docker-base/pull/148>
¹ <https://github.com/nextstrain/docker-base/pull/148#issuecomment-1539203279>
² <https://github.com/nextstrain/docker-base/pull/148#discussion_r1187794955>
> ci: Ignore failures of pathogen-repo-ci builds for now

- .github/workflows/ci.yml
This should fix the currently-broken test-pathogen-repo-ci jobs when our CI runs on master² (and they should continue to work on branches too). It requires a little rearranging of jobs in the workflow, with a little additional and unfortunate complexity due to conditionals.
This works around a Nextstrain CLI bug with registries other than docker.io¹ during `nextstrain update docker` (and `nextstrain setup docker`), which is run as part of our setup-nextstrain-cli action used by this workflow.  Ideally we'll fix that bug and then be able to revert this, especially since we might actually want to condition the pushing to docker.io on the outcome of these test jobs in the future.
¹ <https://github.com/nextstrain/cli/issues/279>
² <https://github.com/nextstrain/docker-base/pull/148#issuecommen …
> ci: Test pathogen repo CI builds using images on docker.io instead of ghcr.io

- .github/workflows/ci.yml
The point is to test the new Docker runtime image, so we don't need to spend the time testing the Conda runtime too.
https://github.com/nextstrain/.github/pull/42
> ci: Only run test-pathogen-repo-ci builds using the Docker runtime

- .github/workflows/ci.yml
- devel/build
This reverts commit 917a04806cffdb76dda815b79479f05b1879e31a and fixes the comment added by efbbfb99c8118ccf0d201aa863c88c8a7bbb4d8d.
We need to cache from ghcr.io because otherwise the build of nextstrain/base doesn't find the layers from the just-built nextstrain/base-builder pushed to ghcr.io.  Instead, it seemingly uses layers from an older nextstrain/base-builder on docker.io.
My understanding is that we were always pulling caches from docker.io (_and_ ghcr.io) because docker.io is the default registry when none is specified, and we use --cache-from lines without a registry specified.
See <https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1683932186614689>.
> Revert "build: Use different cache and output registries"

- Dockerfile
Package maintained by myself to simplify aliasing and dealising of pango lineages
Package is pure Python without dependencies and minimal size
Source code: https://github.com/corneliusroemer/pango_aliasor
See further discussion: https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1683137801980639
Blocking for https://github.com/nextstrain/forecasts-ncov/pull/39
TODO:
> Install pango_aliasor

- Dockerfile
- README.md
- devel/build
- devel/copy-images
- devel/delete-from-ghcr.js
- devel/pull-from-registry
As [noted](https://github.com/nextstrain/docker-base/pull/50#discussion_r986331019) in the PR that introduced multi-platform images, [cross-compilation](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/) can substantially improve multi-platform build time.
- #50
- Naming of Dockerfile stages ([ref](https://github.com/nextstrain/docker-base/pull/98#discussion_r1133001444))
```
% docker pull --platform linux/arm64 nextstrain/base:branch-victorlin-arm64-cross-compilation
% docker run -it --entrypoint /bin/bash nextstrain/base:branch-victorlin-arm64-cross-compilation
nextstrain:~/build $ apt-get update && apt-get install file -y
nextstrain:~/build $ file /usr/local/bin/raxmlHPC-PTHREADS-AVX
/usr/local/bin/raxmlHPC-PTHREADS-AVX: ELF 64-bit LSB …
```
> Use cross-compilation where possible

- Dockerfile
Upgrade to Node.js 16 and remove a redundant Auspice build that [comes with](https://github.com/nextstrain/docker-base/pull/120#issuecomment-1360218169) the upgrade.
- Merge [#98](https://github.com/nextstrain/docker-base/pull/98) which is the target branch of this PR. Otherwise without cross-compilation, Auspice installs/builds are [much slower](https://github.com/nextstrain/docker-base/pull/50#issuecomment-1354247750).
> Upgrade to Node.js 16

- Makefile
- devel/start-localhost-registry
Previously an error occurred if the container existed because container creation tried to use a name already in use.  It's safe to "start" a container that's already started, so this makes the program idempotent.
This also handles the case of the container existing but being stopped, which previously wasn't handled.
> start-localhost-registry: Start container if it already exists

- Dockerfile
This avoids disk-heavy deps like Puppeteer, which bundle a whole Chromium install.  Based on some rough comparisons, I expected this to shave about 600MB from the uncompressed image size and a local test build bore that out.
The node_modules/ tree is infamously large and bloated.  The usual culprits are non-source files that are commonly included in package distributions but not needed at run time.  So there is surely more we could shave off here, but this is a huge easy start.
> Omit dev deps when installing Auspice

- Dockerfile
Node.js v16 will reach end-of-life status on 2023-09-11.
Node.js v18 should also come with performance improvements during run time.
- Prompted by https://github.com/nextstrain/docker-base/pull/122#issuecomment-1590159035
> Upgrade Node.js to v18

- Dockerfile
This build is the only build that runs under emulation in the current multi-platform CI build. The step alone takes upwards of 15 minutes.
Since this is an external tool, pinning to the current latest version seems reasonable. The trade-off is manual version bumps for improved CI build times.
I also hope that CVXOPT will eventually provide wheels for linux/arm64. If/when that happens, the separate installation can be removed entirely.
N/A, I thought of this after seeing build summaries produced by #168. Using that PR as the base of this one to have build summaries here.
> Build CVXOPT in cached section

- Dockerfile
The latest release of evofr included updates to its dependencies that updated the minimum version for jaxlib.¹ I'm using the latest release of jaxlib available in the user forked repo since there's still no official pre-built binaries for linux/arm64.²
I did not realize this change was needed until I saw the "Validate Platform" job fail in the CI run³ that I triggered to update evofr to v0.1.20.
¹ https://github.com/blab/evofr/commit/46f744b605c258d6f3d3b7b3ac8bc877f8e4ba22 
² https://github.com/google/jax/issues/7097
³ https://github.com/nextstrain/docker-base/actions/runs/5480222698
> Update jaxlib for evofr on linux/arm64

- Dockerfile
Adds git back to runtime dependencies to enable cloning of workflow repositories from within a Docker instance. In the short term, this functionality allows use to use GitPod with the base Docker image.
> Add git to runtime dependencies

- Dockerfile
Pin jax version for evofr on linux/arm64 since jax has a minimum version requirement for jaxlib that is _not_ checked by package version constraints in pip.¹ Instead, the jaxlib version is checked at runtime. This led to a mismatch of versions when only pinning jaxlib.²
Also updating both the latest available version of jaxlib in the user forked repo since I'm already updating the Dockerfile. 
¹ https://jax.readthedocs.io/en/latest/jep/9419-jax-versioning.html#how-are-jax-and-jaxlib-versioned
² https://github.com/nextstrain/forecasts-ncov/pull/50#issuecomment-1629841748
Follow-up to https://github.com/nextstrain/docker-base/pull/171
> Jax and jaxlib

- .github/workflows/ci.yml
This is now possible with the addition of example data in the rsv repo¹.
¹ https://github.com/nextstrain/rsv/commit/2efc4b614385a70586f0759ab0cf4600775be187
> Add nextstrain/rsv to CI

- Dockerfile
Since our our last snakemake pin bump ~6 months ago
snakemake has added support for a default profile
that allows reducing required command line flags to
a mininmum. Without default profile, one always either
needs to explicitly specify a profile or set things like
`--cores all` which is very annoying.
Now, you can simply put those flags in `profiles/default/config.yaml`
and they'll automatically be used when you invoke `snakemake`
7.32.3 appears to be reasonably stable, no major bugs reported in a month
I've used it in production for a month now, without issues.
Checklist:
> Bump snakemake pin to 7.32.3

- Dockerfile
If users enter a `nextstrain shell` with this Docker runtime, we want `nextstrain` inside that to use the ambient environment.
Reported by @corneliusroemer in Slack.¹
¹ <https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1694718932379359>
> Configure Nextstrain CLI to use the ambient runtime inside this runtime

- Dockerfile
Required for building the Python isal package (for Augur) when there aren't wheels available (such as with recent version 1.5.2).
> Include Make in builder-target-platform image

- Dockerfile
Augur version 23.1.1 supports versions of pyfastx that provide wheels for Python 3.10.
Note that runtime dependencies are still necessary.
- Follow-up to https://github.com/nextstrain/augur/pull/1335
- Reverts 485b3e5bff48c0bb8f5909dce4cb08990917709a
```sh
nextstrain shell --docker --image=docker.io/nextstrain/base:branch-victorlin-use-prebuilt-pyfastx .
cp /nextstrain/augur/tests/data/aa-seq_h3n2_ha_2y_HA1.fasta .
python -c "import pyfastx; fa = pyfastx.Fasta('aa-seq_h3n2_ha_2y_HA1.fasta'); print(list(fa.keys()))"
```
> Remove pyfastx build dependencies

- Dockerfile
- replace download link with hardcoded alpha version to the link to latest version
- symlink `nextclade` to `nextclade3`, making it default
- either symlink `nextalign` to `nextclade3`, or, preferably, consider removing `nextalign` symlink.
- GitHub release: https://github.com/nextstrain/nextclade/releases/tag/3.0.0-alpha.0
- Slack thread: https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1701151846934669
```
$ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextclade3 --version
nextclade 3.0.0-alpha.0
$ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextclade --version
nextclade 2.14.0
$ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextalign --version
nextalign 2.14.0
$ docker run --rm -it …
```
> Add Nextclade v3 alpha; remove Nextclade v1

- Dockerfile
Issue linked in changes. Pin to an exact version which is known to be compatible.
- https://github.com/nextstrain/augur/issues/1373
> Pin Biopython 1.81

- Dockerfile
See https://github.com/nextstrain/nextclade/releases/tag/3.0.0-alpha.2
Parallel change for conda-base: https://github.com/nextstrain/conda-base/pull/52
> Update `nextclade3` to 3.0.0-alpha.2

- Dockerfile
Unpin Nextclade v3 alpha and use the latest version of Nextclade as default.
Any unmigrated workflows should use `nextclade2` instead of `nextclade`. See the Nextclade v2 → v3 [migration docs](https://docs.nextstrain.org/projects/nextclade/page/user/migration-v3.html) for details.
> Use Nextclade v3

- Dockerfile
This reverts commit "Pin Biopython 1.81" (4edf28247), which is no longer necessary as of Augur version 24.1.0.
<https://github.com/nextstrain/augur/releases/tag/24.1.0>
- Reverts #200
> Unpin Biopython

- .github/workflows/ci.yml
Deprecated and no longer used as setup-python isn't called.
Related-to: <https://github.com/nextstrain/.github/pull/55>
> ci: Remove python-version input to setup-nextstrain-cli action

- Dockerfile
Prompted by internal conversation on Slack¹ that linked to issue indicating csvtk does not treat quotes in TSVs correctly.²
The suggested workaround is to wrap csvtk commands with the new `csvtk fix-quotes` and `csvtk del-quotes` commands. These were added in v0.29.0, so we need to upgrade csvtk here in order to use the workaround. I figured we might as well upgrade to use the latest available version.
Nextstrain conda-base has been using csvtk v0.30.0 since 20240318T235157Z without any issues and I did not see any breaking changes in the csvtk release page.
¹ https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1713392993380609 
² https://github.com/shenwei356/csvtk/issues/130
> Dockerfile: Upgrade csvtk to v0.30.0

- .github/workflows/ci.yml
Pin the `pathogen-repo-ci` to v0, which is before changes for the "smart" workflow were added.
As a future change, we can consider adding a separate job that uses the latest pathogen-repo-ci to test the currently excluded pathogen repos.
Related to https://github.com/nextstrain/.github/issues/93
> ci.yaml: Pin pathogen-repo-ci to v0

- Dockerfile
Otherwise, the awscli → botocore dependency is broken by the subsequent installation of the nextstrain-cli → botocore dependency, which results in --no-sign-request not working as it should.
This approach seemed like the option of least change.  Alternatives to and/or additional improvements to this include a) installing Nextstrain CLI in its own venv instead/as well, b) upgrading to AWS CLI v2 (which is always isolated) or c) updating the nextstrain-cli → botocore dependency to not conflict.
Resolves: <https://github.com/nextstrain/docker-base/issues/213>
Related-to: <https://github.com/nextstrain/docker-base/pull/214>
> Isolate AWS CLI (v1) into its own Python venv

- entrypoint-aws-batch
Snakemake stores state information per input/output here and uses it to determine if it needs to re-run rules or not.  It seems akin to the file mtimes which we already take care to preserve on upload/download. Additionally, the metadata recorded is used in Snakemake's report generation and is generally useful for looking at workflow statistics.
Continue to not upload all of .snakemake/ en masse because it can potentially contain files that interfere with local usage and/or are large and unnecessary.
Resolves: <https://github.com/nextstrain/cli/issues/373>
Related-to: <https://github.com/nextstrain/cli/pull/374>
> entrypoint-aws-batch: Upload .snakemake/metadata/ too

- Dockerfile
Adds pathogen-embed to base image, so we can use its tools for analysis of reassortment in our influenza builds.
https://github.com/nextstrain/conda-base/pull/71
> Add pathogen-embed to the base image

- .github/workflows/ci.yml
Add comments to clearly show the job using pathogen-repo-ci@v0 is for pathogen repos that do not conform to the standard pathogen repo structure. Since these are tied to a old tag of the `pathogen-repo-ci`, the job should not be expected to be updated.
Any new pathogen repos should be added to the `test-pathogen-repo-ci` job which uses the latest version of `pathogen-repo-ci`.
Mirrors changes made in conda-base: https://github.com/nextstrain/conda-base/pull/85
Related to https://github.com/nextstrain/.github/issues/84
> CI: Update test-pathogen-repo-ci

- .github/workflows/ci.yml
**Status: Blocked, awaiting merge of <https://github.com/nextstrain/avian-flu/pull/72>**
Mirrors the change in [avian-flu's CI](https://github.com/nextstrain/avian-flu/pull/72). This PR is on top of #223.
> Update avian flu ci

- Dockerfile
We want the CMAPLE support (first available with 2.3.4) for better and faster trees.
CMAPLE support is optional and not all release builds of IQ-TREE have it enabled.  So far, it seems that the "main" releases are made without CMAPLE support (e.g. 2.3.5) and then parallel releases are made with it (e.g. 2.3.5.cmaple), but only for x86_64 on Linux and macOS.  Thus, we're still not using an aarch64/arm64 binary even though the "main" releases (without CMAPLE support) provide them.  If we keep waiting, maybe they'll start being provided, or, eventually, we can start compiling them ourselves.  That's for another time, though.
Resolves: <https://github.com/nextstrain/docker-base/issues/226>
> Upgrade IQ-TREE to 2.3.5 with CMAPLE support

- Dockerfile
Ideally this would have been added before or as Augur 25.3.0—the first version to include `augur merge`—was packaged into this runtime, but I plain forgot.
> Add the SQLite CLI for `augur merge`

- Dockerfile
Avail ourselves of newer (though still not _new_ ;) software, in particular the SQLite CLI.
> Upgrade base image from Debian Bullseye (oldstable) to Bookworm (stable)

- Dockerfile
manylinux aarch64 wheels are now provided for the CVXOPT version 1.3.2.
- Closes #187
> Remove CVXOPT build

- Dockerfile
Reverts [the dependencies for pangoLEARN added in 2022](https://github.com/nextstrain/docker-base/pull/37) now that pangoLEARN is deprecated.
Closes #157
> Remove pangoLEARN and its dependencies

- Dockerfile
Add dependencies for GenoFLU to run in avian-flu:
- ncbi-blast+
- openpyxl (for pandas.read_excel)
Resolves <https://github.com/nextstrain/docker-base/issues/242>
> Add GenoFLU dependencies

- Dockerfile
- entrypoint-aws-batch
entrypoint-aws-batch: Keep ../ path parts in ZIP archive members during extraction
The default of stripping ../ parts in member paths is a (good!) restriction for safety and security, but such paths do not pose any (additional) risk in the context of our Nextstrain runtime containers. We're already downloading and executing arbitrary user-supplied code, so the ability to potentially overwrite system files with ZIP archive members is not any additional privilege. And it's only potential at that due to most files being owned by root in the image, not the default container user of nextstrain.
Keeping the ../ parts will allow Nextstrain CLI to construct ZIP archives for jobs which write to new sibling paths of /nextstrain/build in the container. This will be used for including pathogen …
> entrypoint-aws-batch: Keep ../ path parts in ZIP archive members during extraction

- Dockerfile
We need support for reading/writing parquet files to prepare submissions to the SARS-CoV-2 variant hub [1]. pandas supports two backends for parquet I/O [2] including pyarrow and fastparquet. The pyarrow library provides a more comprehensive set of tools for the Arrow spec [3], while fastparquet is defined to provide a minimal library for the parquet format.
I've opted for the smaller fastparquet library here, since it provides exactly the functionality we need for an additional 4 MB of Docker image size. The pyarrow library will eventually be a required dependency for pandas [4], so we may eventually need to include to that library. However, pyarrow adds 40 MB to the Docker image size most of which is functionality we don't need.
[1] …
> Add support for reading/writing parquet files with fastparquet

- Dockerfile
We need support for reading/writing parquet files to prepare submissions to the SARS-CoV-2 variant hub [1]. The pyarrow library is one of two supported by pandas [2] along with fastparquet. The pyarrow library provides a more comprehensive set of tools for the Arrow spec [3], while fastparquet is defined to provide a minimal library for the parquet format. I've opted for the larger pyarrow library here, since it will eventually be a required dependency for pandas [4].
[1] https://github.com/nextstrain/forecasts-ncov/issues/132
[2] https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-parquet
[3] https://arrow.apache.org/docs/cpp/user_guide.html
[4] https://pandas.pydata.org/pdeps/0010-required-pyarrow-dependency.html
https://github.com/nextstrain/forecasts-ncov/issues/132
> Add support for reading/writing parquet files with pyarrow

- Dockerfile
This is the earliest version supported by current versions of Auspice.
Follow-up to https://github.com/nextstrain/auspice/commit/b271201383e256be389cb01936f08955f1c82944
```
$ nextstrain shell --docker --image nextstrain/base:branch-victorlin-nodejs-20 . -c "node --version"
v20.19.3
```
> Upgrade Node.js to v20

- entrypoint-aws-batch
When using Snakemakes storage support to download remote files, Snakemake stores 
the downloaded files in `.snakemake/storage` by default. This allows users to 
keep the remote files that were downloaded during the build on AWS Batch.
Note that the storage path is configurable via Snakemake's 
`--local-storage-prefix`.¹ So if someone configures the storage path to a custom 
path within `.snakemake`, e.g. `.snakemake/foo`, then it would not be available 
in their workdir. I'm not sure it's even possible to make this path configurable 
here, so I'm just going to warn against using it from the Nextstrain CLI. 
Related to https://github.com/nextstrain/cli/pull/460
¹ <https://github.com/snakemake/snakemake/blob/v9.6.3/src/snakemake/cli.py#L1456-L1462>
> entrypoint-aws-batch: Upload .snakemake/storage/ too 

- Dockerfile
Since evofr v0.1.27, there is a CLI that can be used to run the model. This makes the executable available so that we can directly run the evofr commands.
Related to https://github.com/nextstrain/forecasts-ncov/issues/134
> Make evofr executable available

- Dockerfile
Resolves #177
Image size increase should be <1MB unless some libraries are added as well (we'll see in CI):
```bash
$ du -h | grep vim
12K     ./etc/vim
4.0K    ./var/lib/vim/addons
8.0K    ./var/lib/vim
12K     ./usr/share/bug/vim-tiny
32K     ./usr/share/doc/vim-common
32K     ./usr/share/doc/vim-tiny
16K     ./usr/share/vim/vim82/doc
24K     ./usr/share/vim/vim82
28K     ./usr/share/vim
$ du -h | grep nano
4.0K    ./usr/share/doc/nano/examples
12K     ./usr/share/doc/nano
36K     ./usr/share/nano/extra
196K    ./usr/share/nano
4.0K    ./nextstrain/.local/share/nano
```
> Add nano and vim-tiny for usability in interactive prompt

- .github/workflows/ci.yml
This repo has been reworked to be compatible with the newer pathogen-repo-ci and thus no longer works with pathogen-repo-ci-v0.
I chose not to check the new version because it is still in progress. The only check would be on an [unstable](https://github.com/nextstrain/ebola/issues/20) and [long-running](https://github.com/nextstrain/ebola/pull/15#issuecomment-3286017943) ingest workflow, which doesn't seem useful to include here as-is.
Follow-up to https://github.com/nextstrain/ebola/pull/16#pullrequestreview-3218960692
> Remove ebola repo check
