nextstrain/docker-base

Dockerfile, auspice-wrapper
=> Pre-compile auspice and run the non-dev server for a better experience

Dockerfile
At Richard's request to facilitate integration of Nextalign into the ncov builds.
---
I'm going to let Travis build this as `nextstrain/base:branch-nextalign` and then test it out before merging.
=> Add Nextalign

Dockerfile
update treetime to the version that handles amino acid reconstructions properly.
=> chore: update treetime

Dockerfile
fix:nextalign got integrated into nextclade, this fixes the download url
=> fix:nextalign got integrated into nextclade, this fixes the download url

Dockerfile
Upgrades Nextclade and Nextalign to final release 2.0.0
=> Upgrade nextclade to 2.0.0

.github/workflows/ci.yml
=> ci: Run zika-tutorial workflow before Docker push

.github/workflows/ci.yml
=> Revert "ci: Run zika-tutorial workflow before Docker push"

.github/workflows/ci.yml
_(#59 take 2)_
Run the zika-tutorial workflow for all CI runs. Also adding a little re-organization of the CI file.
- Closes #56
- Closes #61
See passing checks on 0bd82d823573ebe9a4b1125b96ce81a97a1db904 and failing checks on e14edbf6952a0e5309dee2171c0d36b6c986bf2a.
=> ci: Run zika-tutorial workflow as an integration test

Dockerfile
=> feat: add zstd to runtime installs

devel/build
Added a comment to clarify behavior. A comment was in the commit message of 6ae4036618b1b7c5f06a32c66487b2c7481da0f8 but it was lost during rebase.
Related to https://github.com/nextstrain/docker-base/pull/49#discussion_r922572801
=> Add note on persistent builder

Dockerfile, entrypoint
=> Run as non-root "nextstrain" user and set HOME=/nextstrain

Dockerfile, entrypoint
See commit messages for details.
Related to #83
=> Non-root user, deux

Dockerfile
=> Update builder-scripts/ COPY command, consolidate other commands

Dockerfile
Add pysam pin, move it, and add some clarity.
_N/A_
=> Update pip pins

Dockerfile
resolves #52 (see there for discussion)
=> chore: unpin nextstrain cli

README.md, devel/pull-from-registry
This script isn't used by CI, but it is useful for local dev as mentioned in the README update.
- Follow-up to #103
=> Add convenience script to pull images for local use

Dockerfile, README.md
_[(preview)](https://github.com/nextstrain/docker-base/tree/victorlin/add-instructions-for-new-program#adding-a-new-software-program)_
See commits.
_N/A_
_N/A, docs change._
=> Add instructions for adding a new program

Dockerfile
The latest version of Auspice supports Node.js v16. This should come with performance improvements.
- Release new version of Auspice which contains changes necessary for the image to build properly (see failing CI for details).
_N/A_
=> Bump Node.js to v16

.github/workflows/ci.yml
Use new token and remove unnecessary encryption of username.
- https://github.com/nextstrain/private/issues/73
=> Update Docker Hub login

Dockerfile, README.md
See commit messages and updates to README.
N/A
=> Update shell usage

Dockerfile, README.md, devel/build
A few small things I noticed while working on these files. See commit messages.
_N/A_
=> Small improvements

.github/workflows/ci.yml, devel/build, devel/validate-platforms, entrypoint-aws-batch
Linting that helps spot errors.  I'll resolve what it finds in subsequent commits.
=> ci: Shellcheck

.gitignore, Makefile, README.md, devel/clean, devel/start-localhost-registry
Fixes for things I ran into during recent local dev sessions. See commit messages for details.
=> Improve storage for local dev

.github/workflows/ci.yml, Dockerfile, create-envd, delete-envd, devel/build, drop-privs, entrypoint, entrypoint-aws-batch, tests/envdir-url.t, tests/envdir.t
See commit messages.
Envdir support is useful in the general case, but specifically added now to enable [better facilities for environment variables in Nextstrain CLI](https://github.com/tsibley/blab-standup/blob/master/2023-06-02.md).
=> Envdir support

.github/workflows/ci.yml, devel/delete-from-ghcr.js
See commit messages.
- (Hopefully) fixes #131
We'll need a few runs to see if errors go away, either because of this fix or GitHub coincidentally fixes something on their end.
=> Don't delete the GHCR package

.github/workflows/ci.yml, .gitignore, devel/build, devel/clean, devel/summarize-buildkit-output
Add a script that extracts useful information from BuildKit output, use it on all 3 stages of the Docker build, and put it in the GitHub job summary.
N/A, motivated by myself getting frustrated at how hard it is to inspect the logs for layer build times.
=> Summarize build execution times in CI

.github/workflows/ci.yml
Reasoning is the same as in https://github.com/nextstrain/augur/commit/5aba7ec9b3b1c3c676c3f2b850d1148061de7340.
=> Temporarily disable monkeypox CI

.github/workflows/ci.yml
This is the preferred way of installation.
Addresses failing test in #189 ([link](https://github.com/nextstrain/docker-base/actions/runs/6724261277/job/18277692042?pr=189#step:10:367)).
=> Use central action to setup Nextstrain CLI

Dockerfile
The previous installation scripts are no longer supported, and there is a [new installation method](https://github.com/nodesource/distributions/blob/4f746d991e099f9494b12e275abe1aab21f1ddf0/README.md#new-update-%EF%B8%8F).
- Resolves #188
=> Update Node.js installation method

.github/workflows/ci.yml
Not used currently but doesn't hurt to change anyways.
Related-to: <nextstrain/mpox#168>
=> CI: Update mpox repo name

Dockerfile
Upgrade nextclade to 3.0.0-alpha.1
#195
=> Upgrade nextclade to 3.0.0-alpha.1

Dockerfile
- Parallels https://github.com/nextstrain/conda-base/pull/53
- [Slack discussion](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1705086544738269)
=> Pin pulp<2.8 for snakemake

.github/workflows/ci.yml
Repurpose and move related comment + disabling of mpox to the bottom of the pathogen list.
- https://github.com/nextstrain/.github/issues/63
=> Temporarily disable zika CI

.github/workflows/ci.yml
Mirrors the change in avian-flu's CI.
- https://github.com/nextstrain/avian-flu/pull/17
=> Reference new CI target

Dockerfile
Resolves https://github.com/nextstrain/docker-base/issues/218
=> Support Snakemake --report

Dockerfile
Update to the latest release of pathogen-embed with bug fixes, new encoding for PCA embeddings, and new input for clustering.
=> Bump pathogen-embed to 2.3.0

.github/workflows/ci.yml
Based on https://github.com/nextstrain/docker-base/pull/223
Blocked on merge of https://github.com/nextstrain/lassa/pull/8
=> Update lassa CI

Dockerfile
Bumps pathogen-embed to 3.0.0.
=> Bump pathogen-embed to 3.0.0

.github/workflows/ci.yml
Part of https://github.com/nextstrain/docker-base/issues/238
=> CI: add new pathogens to `test-pathogen-repo-ci`

.github/workflows/ci.yml
Follow up on <https://github.com/nextstrain/avian-flu/pull/103>
Part of https://github.com/nextstrain/public/issues/20
=> CI/test-pathogen-repo-ci-v0: fix avian-flu build-args

.github/workflows/ci.yml
=> Update mumps CI

Dockerfile
To be used by data ingestion workflows.
=> Add bio command line tool

Dockerfile
This should have been a part of #248.
`nextstrain shell --docker --image=docker.io/nextstrain/base:branch-victorlin-bio . -c 'bio'`
=> Make bio executable available

Dockerfile
This contains support for `bio json --lines`.
- https://github.com/ialbert/bio/pull/38
- https://github.com/nextstrain/pathogen-repo-guide/issues/84#issuecomment-2857331465
=> Bump bio to version 1.8.0

Dockerfile
Resolves https://github.com/nextstrain/docker-base/issues/256
Upgrade to Snakemake v9.6.2
=> Upgrade to Snakemake v9

.github/workflows/ci.yml
The rsv repo now has a CI-specific config file.
https://github.com/nextstrain/rsv/issues/104
=> CI: Add build args for rsv CI
